# Generated by Django 4.1.7 on 2023-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.FloatField()),
                ('phone', models.CharField(max_length=2500)),
                ('bookname', models.CharField(max_length=250000)),
                ('Authorname', models.CharField(max_length=2500)),
            ],
        ),
    ]
