# Generated by Django 4.1.7 on 2023-03-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
