# Generated by Django 4.1.7 on 2023-02-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='MyModel',
        ),
    ]
