# Generated by Django 4.1.7 on 2023-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_books_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
                ('bprice', models.FloatField()),
                ('author', models.CharField(max_length=255)),
                ('story', models.CharField(max_length=2500)),
            ],
        ),
    ]
