# Generated by Django 4.1.7 on 2023-03-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
