# Generated by Django 4.1.7 on 2023-03-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_delete_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=2500)),
            ],
        ),
    ]
